#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION=run
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  run)
    cd "$THIS_DIR"
    mkdir -p tmp/in tmp/out
    local +x args="--release --no-debug"
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

