#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
local +x ACTION=$1; shift

case "$ACTION" in

  run)
    cd "$THIS_DIR"
    mkdir -p tmp/in tmp/out
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

